# Generated by Django 4.1.2 on 2022-10-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SISWA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NISN', models.CharField(max_length=50)),
                ('NAMA', models.CharField(max_length=40)),
                ('TTL', models.CharField(max_length=40)),
                ('PHOTO', models.CharField(max_length=40)),
                ('EMAIL', models.CharField(max_length=40)),
                ('NILAI', models.CharField(max_length=40)),
                ('ALAMAT', models.CharField(max_length=40)),
            ],
        ),
    ]
